apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - prometheus-community.yaml
  - democratic-csi.yaml
  - grafana.yaml
  - traefik.yaml
  - jetstack.yaml
  - mittwald.yaml
  - sealed-secrets.yaml
  - k8s-at-home.yaml
  - openebs.yaml
  - utkuozdemir.yaml
  - vmware-tanzu.yaml
  - nvidia.yaml
  - bjw-s.yaml
  - k8s-home-lab.yaml
  - bitnami-mariadb.yaml
  - tailscale.yaml
  - metallb.yaml
