apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-cloudflare-api-token-secret.json
  - sealed-traefik-basic-auth.json
  - sealed-traefik-sso.json
  - sealed-plex.json
  - sealed-rtsptoweb.json
  - sealed-brother-ssh.json
  - sealed-tailscale-oauth.json
