apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-cloudflare-api-token-secret.json
  - sealed-traefik-basic-auth.json
  - sealed-traefik-sso.json
  - sealed-cloudflare-ddns.json
  - sealed-plex.json
  - sealed-chevereto-mariadb.json
  - sealed-prometheus-access-token.json
  - sealed-unifi-poller.json
  - sealed-kube-prometheus-stack-grafana.json
  - sealed-kube-prometheus-stack-grafana-smtp.json
  - sealed-b2-credentials.json
  - sealed-rtsptoweb.json
  - sealed-brother-ssh.json
