apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - sealed-secrets
  - kubernetes-replicator
  # - democratic-csi
  - metallb
  - traefik
  - cert-manager
  - openebs
  - node-feature-discovery
  - intel-gpu-plugin
  - velero
  - nvidia
  - tailscale
